name: e_commers
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  animate_do: ^2.0.0
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_rating_bar: ^4.0.0
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^1.0.0
  form_field_validator: ^1.1.0
  google_fonts: ^2.1.0
  http: ^0.13.4
  image_picker: ^0.8.4+4
  permission_handler: ^8.3.0
  shimmer: ^2.0.0
  timeago: ^3.1.0
  sizer: ^2.0.15
  sensors_plus: ^1.3.0
  flutter_local_notifications: ^9.4.0
  timezone: ^0.8.0
  floor: ^1.2.0
  dots_indicator: ^2.0.0
  flutter_staggered_grid_view: ^0.4.1
  auto_size_text: ^3.0.0
  email_validator: ^2.0.1
  responsive_framework: ^0.1.7
  awesome_notifications: ^0.0.6+7
  shake: ^2.0.0
  all_sensors: ^0.3.1+2
  motion_toast: ^2.1.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  floor_generator: ^1.2.0
  build_runner: ^2.1.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/products/banner/
    - assets/banner/
    # - assets/svg/
    - assets/products/dairy/
    - assets/products/vegetables/
    - assets/products/fruits/
    # - assets/products/users/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
